---
############
#Add objects
############


- include: bigip_iapp_template/appsvcs.yml
  when: state == "present"

- include: bigip_iapp_service/app1_svc.yml
  when: state == "present"
  
- include: bigip_iapp_service/app2_svc.yml
  when: state == "present"
  
- include: bigip_iapp_service/app3_svc.yml
  when: state == "present"

###############
#Remove objects
###############


- include: bigip_iapp_service/app1_svc.yml
  when: state == "absent"
  
- include: bigip_iapp_service/app2_svc.yml
  when: state == "absent"  
  
- include: bigip_iapp_service/app3_svc.yml
  when: state == "absent" 
  
- include: bigip_iapp_template/appsvcs.yml
  when: state == "absent"
...
